---
- name: Install Updates
  tags: always
  apt:
    upgrade: dist
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install OpenJDK (required by Elasticsearch and Kibana)
  apt:
    name: openjdk-11-jre-headless
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Download and install Elasticsearch DEB package
  get_url:
    url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.15.0-amd64.deb
    dest: /tmp/elasticsearch.deb
  when: ansible_distribution == "Ubuntu"

- name: Install Elasticsearch
  apt:
    deb: /tmp/elasticsearch.deb
  when: ansible_distribution == "Ubuntu"

- name: Enable and start Elasticsearch service
  service:
    name: elasticsearch
    enabled: yes
    state: started
  when: ansible_distribution == "Ubuntu"

- name: Download and install Kibana DEB package
  get_url:
    url: https://artifacts.elastic.co/downloads/kibana/kibana-7.15.0-amd64.deb
    dest: /tmp/kibana.deb
  when: ansible_distribution == "Ubuntu"

- name: Install Kibana
  apt:
    deb: /tmp/kibana.deb
  when: ansible_distribution == "Ubuntu"

- name: Enable and start Kibana service
  service:
    name: kibana
    enabled: yes
    state: started
  when: ansible_distribution == "Ubuntu"

- name: Download and install Logstash DEB package
  get_url:
    url: https://artifacts.elastic.co/downloads/logstash/logstash-7.15.0-amd64.deb
    dest: /tmp/logstash.deb
  when: ansible_distribution == "Ubuntu"

- name: Install Logstash
  apt:
    deb: /tmp/logstash.deb
  when: ansible_distribution == "Ubuntu"

- name: Enable and start Logstash service
  service:
    name: logstash
    enabled: yes
    state: started
  when: ansible_distribution == "Ubuntu"

- name: Set up Elasticsearch Authentication
  command: grep -q '^xpack.security.enabled:false$' /etc/elasticsearch/elasticsearch.yml
  register: xpack_security_check
  changed_when: false
  failed_when: false
  when: ansible_distribution == "Ubuntu"

- name: Add xpack.security.enabled if not present
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    line: 'xpack.security.enabled: false'
  when: ansible_distribution == "Ubuntu" and xpack_security_check.rc != 0 

- name: Restart Elasticsearch
  service:
    name: elasticsearch
    state: restarted
  when: ansible_distribution == "Ubuntu"

- name: Set up HTTPS for Elasticsearch
  blockinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    block: |
      xpack.security.http.ssl.enabled: true
      xpack.security.http.ssl.key: /etc/elasticsearch/private.key
      xpack.security.http.ssl.certificate: /etc/elasticsearch/certificate.crt
      xpack.security.http.ssl.certificate_authorities: /etc/elasticsearch/ca-certificates.crt
  when: ansible_distribution == "Ubuntu"

- name: Restart Elasticsearch
  service:
    name: elasticsearch
    state: restarted
  when: ansible_distribution == "Ubuntu"

- name: Set up Kibana Authentication
  stat:
    path: /etc/kibana/kibana.yml
  register: auth_check
  when: ansible_distribution == "Ubuntu"

- name: Add Elasticsearch Uname and Pword to Kibana Config
  blockinfile:
    path: /etc/kibana/kibana.yml
    block: |
      elasticsearch.username: "qmjaejercito"
      elasticsearch.password: "2111419"
  when: ansible_distribution == "Ubuntu" and auth_check.stat.exists

- name: Restart Kibana
  service:
    name: kibana
    state: restarted
  when: ansible_distribution == "Ubuntu"

- name: Allow Elasticsearch Port
  ufw:
    rule: allow
    port: 9200
    proto: tcp
  when: ansible_distribution == "Ubuntu"

- name: Allow Kibana Port
  ufw:
    rule: allow
    port: 5601
    proto: tcp
  when: ansible_distribution == "Ubuntu"

- name: Reload Firewall
  ufw:
    state: reloaded
  when: ansible_distribution == "Ubuntu"

